### ISSUE TITLE
HTTPRequest.Multipart.Content not working 

### ISSUE THREAD

**Issue by siddharth952** [vmanot/NetworkKit#2]
I am passing all of the required data to upload to the cloud server, but is this not working? The logic was working for older versions of NetworkKit which had the 'Task' package as a dependency 
 
 
 Tried out other ways in the package to send the media but that did not work
 
 ```
   public func createHTTPRequestBody() throws -> HTTPRequest.Body? {
         if case let .uploadImage(imageData) = self {
            var content = HTTPRequest.Multipart.Content(type: .formData, parts: [
                HTTPRequest.Multipart.Part.formData(
                name: "image",
                fileData: imageData,
                fileName: "image.jpeg",
                contentType: "image/*"
            )])
            let body = HTTPRequest.Body.data(content.body)
            return body
        }
}
```

**creating httpHeader:**

 ```
   var httpHeader: HTTPRequest.Header {
        var header = HTTPRequest.Header()
   
        switch self {
            case .uploadSpl:
                header.append(.contentType(.custom("image/jpeg")))
                return header
            default:
                header.append(.custom(key: "X-APP-VERSION", value: "\(666)"))
                header.append(.authorization(.custom("Token"), token))
        }
        
        switch self {
            case .uploadImage
                return header
            default:
                break
        }
```

**Comment by siddharth952** [comment]
Also the headers are being removed by using this block of code:

 ```
          let body = HTTPRequest.Body.data(content.body)
           return body
```

**Comment by fampaySiddharth** [comment]
![Screenshot 2023-06-19 at 2 20 45 PM](https://github.com/vmanot/NetworkKit/assets/92845187/ac7a103e-add5-40f0-a1cb-850781108738)

**Comment by siddharth952** [comment]
![Screenshot 2023-06-19 at 2 20 45 PM](https://github.com/vmanot/NetworkKit/assets/40488679/d3feed0e-71a1-4c14-aa30-e78dc693ccb7)

Using this approach I get back the following from the server which I was not getting before:
data: {"detail":"Unsupported media type \"\" in request."}

**Comment by fampaySiddharth** [comment]
Any updates on this?

**Comment by siddharth952** [comment]
This can be solved by creating another constructor that retains the headers when we cast it to Data

```
        public static func data(_ data: Data) -> Self {
            .init(header: [], content: .data(data))
        }
        // We add this
        public static func dataWithHeader(_ data: Data, headers: [HTTPHeaderField]) -> Self {
            .init(header: headers, content: .data(data))
        }
```

**Comment by vmanot** [comment]
@siddharth952 awesome. I'll add this convenience method as well, should solve the issue then?

**Comment by siddharth952** [comment]
Yes, adding the convenience method will fix the issue.

**Comment by vmanot** [comment]
Added a `HTTPRequest.Body.data(_:headers)` constructor.
