### ISSUE TITLE
Network call os_unfair_lock_lock

### ISSUE THREAD

**Issue by siddharth952** [vmanot/NetworkKit#3]
If a network call fails for some reason then it causes os_unfair_lock_lock(base).

eg. Use of @ReactorRepository() var repository: UserRepository
```
public func registerDevice() -> AnyPublisher<GenericRequestResponse, Error> {
        return serverSession
            .task(with: .registerDevice)
            .successPublisher
            .tryMap({ try $0.unwrap(GenericRequestResponse.self) })
            .eraseToAnyPublisher()
    }
    
        func task(for action: Action) -> ActionTask {
        switch action {
        case .registerDevice: do {
            return repository.registerDevice()
                // .receiveOnMainQueue() Adding this is also not helping
                .eraseToActionTask()
        }
```

This is due to usage (Merge package's ) sinkResult. As earlier removing it used to help get rid of this problem at other places.

**Comment by vmanot** [comment]
@siddharth952 which commit of `Reactor` and `Merge` are you using? Am closing this issue as it's unrelated to `NetworkKit` from what I understand, please reopen it on Merge.
